micronaut:
  application:
    name: MicronautAWSTemplate
    #https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#metricsAnnotations
  metrics:
    enabled: true
    binders:
      processor:
        enabled: false
      uptime:
        enabled: false
      logback:
        enabled: false
      jdbc:
        enabled: false

  session:
    http:
      cookie: true
      header: true
netty:
  default:
    allocator:
      max-order: 3

#These are the values from the CDK stack
aws:
  region: "us-west-1"
  appRoleArn: "arn:aws:iam::035898927414:role/appRole"

ddbtablenames:
  person: people
