
#Options for nice debug endpoints
# https://docs.micronaut.io/latest/guide/#providedEndpoints
endpoints:
  routes:
    enabled: true
    sensitive: false
micronaut:
  application:
    name: MicronautAWSTemplate
    #https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#metricsAnnotations
  metrics:
    enabled: true
    binders:
      processor:
        enabled: false
      uptime:
        enabled: false
      logback:
        enabled: false
      jdbc:
        enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/*
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
        #For some reason the swagger UI fails to load with 404 trying to look into res, adding res explicitly fixes it
      res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /res/**

  session:
    http:
      cookie: true
      header: true
netty:
  default:
    allocator:
      max-order: 3

#These are the values from the CDK stack
aws:
  region: "us-west-1"
  appRoleArn: "arn:aws:iam::475393585810:role/appRole"

ddbtablenames:
  person: people
